### ISSUE TITLE
CMake build issue

### ISSUE THREAD

**Issue by cvolpe** [Lucaweihs/range-tree#1]
I just cloned the repo and tried to build this with no mods. I manually created the "build" dir, and followed the instructions to cd into build, and then run "cmake ..". Here's the output from cmake:

D:\Volpe\Geolocation\Luca_Weihs_range-tree\build>cmake ..
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.25.28612.0
-- The CXX compiler identification is MSVC 19.25.28612.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
CMake Error at CMakeLists.txt:48 (add_executable):
  No SOURCES given to target: RangeTree_prof

CMake Generate step failed.  Build files cannot be regenerated correctly.

Any thoughts?

**Comment by rconnorlawson** [comment]
I also had issues building with CMake out of the box. I use GCC v8.4.0 on Ubuntu 16.04. I had to modify several things: 

* Comments the "Profiling" section in CMakeLists.txt, since the source file (mentioned in your error) does not exist in the repo.
* Remove `-ansi` flag, since it appears to override the `-std=c++11` on my compiler
* Include the `<algorithm>` header (for `std::sort`)
* Change the definition of `GTEST_LIBS_DIR` in `ext/gtest/CMakeLists.txt` to `${binary_dir}/lib` to fix linker errors.

All of this was done by trial and error, poking around inside the CMakeLists.txt to remove troublesome lines and inside the `build` directory to find the missing binaries. After the noted modifications, the library built correctly and all tests passed.

It's worth noting that the library is header-only, so you don't really need the build system to work in order to use it. The whole functionality is in `RangeTree.h`.

If OP is still looking for an answer, it seems that [this fork](https://github.com/peter0749/range-tree) includes effectively the same changes as I mentioned above.

**Comment by cvolpe** [comment]
No longer looking for an answer. Thanks for your help!

**Comment by Lucaweihs** [comment]
Hi @rconnorlawson, @cvolpe,

I haven't been actively maintaining this repository but am happy to look over any pull request to integrate these changes if either of you would like to make one.

**Comment by rconnorlawson** [comment]
Thanks! I'll push something shortly.
